# Generated by Django 3.2.13 on 2022-06-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webVoite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='floor',
            field=models.CharField(blank=True, choices=[('B', 'Мальчик'), ('G', 'Девочка')], max_length=20),
        ),
    ]
